// Downloads the latin-subset woff2 files for the two brand fonts from Google Fonts
// and emits src/styles/fonts.css with self-hosted @font-face rules (stable /fonts/ URLs).
// Run once: `node scripts/fetch-fonts.mjs`. Re-run only if weights change.
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_FONTS = join(ROOT, "public", "fonts");
const OUT_CSS = join(ROOT, "src", "styles", "fonts.css");
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36";

const families = [
  "Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500",
  "DM+Sans:wght@300;400;500"
];

await mkdir(OUT_FONTS, { recursive: true });

let css = "/* Self-hosted brand fonts (latin subset). Generated by scripts/fetch-fonts.mjs. */\n";
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

for (const fam of families) {
  const url = `https://fonts.googleapis.com/css2?family=${fam}&display=swap`;
  const sheet = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => r.text());
  // Google emits one @font-face per unicode-range subset, each preceded by a /* subset */ comment.
  const blocks = sheet.split("/*").map((b) => "/*" + b);
  for (const block of blocks) {
    const subset = block.match(/\/\*\s*([a-z0-9-]+)\s*\*\//i)?.[1];
    if (subset !== "latin") continue; // English site → latin only
    const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
    const style = block.match(/font-style:\s*(\w+)/)?.[1] || "normal";
    const src = block.match(/url\(([^)]+\.woff2)\)/)?.[1];
    if (!family || !weight || !src) continue;
    const name = `${slug(family)}-${weight}${style === "italic" ? "-italic" : ""}.woff2`;
    const buf = Buffer.from(await fetch(src, { headers: { "User-Agent": UA } }).then((r) => r.arrayBuffer()));
    await writeFile(join(OUT_FONTS, name), buf);
    // No unicode-range: we ship a single subset per weight, so let the browser use the
    // font for every glyph it actually contains (incl. ₹ U+20B9) and fall back otherwise.
    css +=
      `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};` +
      `font-display:swap;src:url('/fonts/${name}') format('woff2')}\n`;
    console.log("  saved", name, (buf.length / 1024).toFixed(1) + "KB");
  }
}

await writeFile(OUT_CSS, css);
console.log("wrote", OUT_CSS);
