import { readFileSync, readdirSync, existsSync } from "node:fs";
import { resolve } from "node:path";

// Academy entries are published JSON artifacts (schema academy-1), generated by
// scripts/academy/generate-entry.mjs and promoted into data/academy/<locale>/.
// Read at build time from the repo root (Astro build cwd), mirroring how the rest
// of the site treats data/ as the canonical artifact store.

export type AcademyKeyTerm = { term: string; plainMeaning: string };
export type AcademyPullQuote = { quote: string; afterHeading?: string };
export type AcademyVisualSegment = { label: string; value: number };
export type AcademyVisual = {
  type: string;
  title?: string;
  subtitle?: string;
  afterHeading?: string;
  segments?: AcademyVisualSegment[];
  source?: string;
};
export type AcademyLink = { match: string[]; url: string };
export type AcademyEntry = {
  slug: string;
  title: string;
  track?: string;
  module?: string;
  depth?: string;
  standfirst?: string;
  bottomLine?: string;
  body?: string;
  pullQuotes?: AcademyPullQuote[];
  visuals?: AcademyVisual[];
  keyTerms?: AcademyKeyTerm[];
  onTheGround?: { heading?: string; body?: string };
  whatPeopleGetWrong?: string;
  caveat?: string;
  connects?: string[];
  sources?: string[];
  status?: string;
};

function loadDir(locale: string): AcademyEntry[] {
  const dir = resolve("data/academy", locale);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => JSON.parse(readFileSync(resolve(dir, f), "utf8")) as AcademyEntry);
}

// Sort by module label ("1 — The Idea" < "6 — The Production Side") then title, so
// index listings read in curriculum order without a separate manifest.
function byModuleThenTitle(a: AcademyEntry, b: AcademyEntry) {
  const m = String(a.module || "").localeCompare(String(b.module || ""), undefined, { numeric: true });
  return m !== 0 ? m : String(a.title).localeCompare(String(b.title));
}

export const academyEntries: AcademyEntry[] = loadDir("en").sort(byModuleThenTitle);

// Vetted external link map (figures, events, institutions, the cited paper). URLs are
// hand-curated and verified to resolve — never model-generated — then auto-applied to
// the first mention in an entry's prose.
export const academyLinks: AcademyLink[] = existsSync(resolve("data/academy/links.json"))
  ? (JSON.parse(readFileSync(resolve("data/academy/links.json"), "utf8")) as AcademyLink[])
  : [];
export const academyBySlug: Record<string, AcademyEntry> = Object.fromEntries(
  academyEntries.map((e) => [e.slug, e])
);

export function academyUrl(slug: string) {
  return `/academy/${slug}/`;
}

// Group by module for the index page.
export function academyByModule(): Array<{ module: string; entries: AcademyEntry[] }> {
  const groups = new Map<string, AcademyEntry[]>();
  for (const e of academyEntries) {
    const key = e.module || "Other";
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(e);
  }
  return [...groups.entries()].map(([module, entries]) => ({ module, entries }));
}
